name: Git Push Workflow Mechanisms
on:
  push:
    branches: [main]
jobs:
  build:
    permissions: 
      contents: read
      packages: write 
      
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        
    - name: Tag Identification
      id: tag_version
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
        WITH_V: true
        DRY_RUN: true
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Maven Set Package version
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
      run: mvn versions:set -DnewVersion=${{ steps.tag_version.outputs.new_tag }}

    - name: Maven Build
      run: mvn -B package --file pom.xml    
    
    - name: Publish to GitHub Packages Apache Maven
      run: mvn --batch-mode -DskipTests -DuseGitHubPackages -DsignArtifacts -Pgithub-releases deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
   
    - name: Release Creation
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        release_name: Release ${{ steps.tag_version.outputs.new_tag }}
        draft: false
        prerelease: false
    
    - name: Tag Creation
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
        WITH_V: true
        CUSTOM_TAG: ${{ steps.tag_version.outputs.new_tag }}


